#!/bin/bash

cat > test << EOF
FROM openjdk:11-jre-slim
ADD ./target/${ECR_IMAGE}.jar /home/${ECR_IMAGE}.jar
CMD ["nohup", "java", "-jar", "-Dspring.profiles.active='mysql'", "/home/${ECR_IMAGE}.jar"]
EOF

